/**
 * Block registry. Block ids are stored as Uint8 in chunk data. Each block maps
 * to texture-array layers (top / side / bottom) generated by TextureGen.
 * Pure data: imported by both workers and the main thread.
 */

export enum L {
  ROCK, BASALT, SOIL, MOSS_TOP, MOSS_SIDE, SAND, SNOW, ICE, IRON_ORE, COPPER_ORE,
  QUARTZ, CARBON, TITANIUM_ORE, RADITE, AURELITE, LAVA, METAL_PLATE, GLASS, CONCRETE, LAMP,
  SANDSTONE, ASH, SULFUR, STALK, CANOPY, MUD, BEDROCK, CRYOLITH, LUMINITE, REGOLITH,
  FLOOR, CORAL, SNOW_SIDE, HULL, FUNGUS, RED_ROCK, STALK_TOP, COUNT,
}

export const LAYER_COUNT = L.COUNT as number;

export enum B {
  AIR = 0, BEDROCK, ROCK, BASALT, SOIL, MOSS, SAND, SNOW, ICE, IRON_ORE,
  COPPER_ORE, QUARTZ, CARBON, TITANIUM_ORE, RADITE, AURELITE, LAVA, METAL_PLATE, GLASS, CONCRETE,
  LAMP, SANDSTONE, ASH, SULFUR, STALK, CANOPY, MUD, CRYOLITH, LUMINITE, REGOLITH,
  FLOOR, CORAL, FUNGUS, RED_ROCK, HULL,
  /** invisible solid cell owned by a machine entity */
  MACHINE = 250,
  /** invisible passable cell owned by a machine entity (open door) */
  MACHINE_OPEN = 251,
  UNKNOWN = 255,
}

export interface BlockDef {
  id: number;
  key: string;
  name: string;
  top: number;
  side: number;
  bottom: number;
  /** seconds to break with the Mk1 extractor */
  hardness: number;
  /** minimum extractor tier */
  tier: number;
  drop: string | null;
  dropCount: number;
  solid: boolean;
  opaque: boolean;
  /** rendered in the translucent pass */
  translucent: boolean;
  /** emissive strength (linear HDR multiplier of albedo) */
  emissive: number;
  /** footstep / mining sound family */
  sound: 'rock' | 'soil' | 'sand' | 'snow' | 'ice' | 'metal' | 'glass' | 'crystal' | 'organic';
  /** shows up highlighted by the geological scanner */
  ore: boolean;
  /** radiation emitted (arbitrary units at 1 m) */
  radiation: number;
}

const defs: BlockDef[] = [];

function def(id: number, key: string, name: string, layers: [number, number, number] | number, o: Partial<BlockDef> = {}): void {
  const [top, side, bottom] = typeof layers === 'number' ? [layers, layers, layers] : layers;
  defs[id] = {
    id, key, name, top, side, bottom,
    hardness: 0.6, tier: 1, drop: key, dropCount: 1, solid: true, opaque: true,
    translucent: false, emissive: 0, sound: 'rock', ore: false, radiation: 0,
    ...o,
  };
}

def(B.AIR, 'air', 'Vácuo', 0, { solid: false, opaque: false, drop: null });
def(B.BEDROCK, 'bedrock', 'Manto Planetário', L.BEDROCK, { hardness: Infinity, drop: null, tier: 99 });
def(B.ROCK, 'rock', 'Rocha', L.ROCK, { hardness: 0.75 });
def(B.BASALT, 'basalt', 'Basalto', L.BASALT, { hardness: 0.95 });
def(B.SOIL, 'soil', 'Solo', L.SOIL, { hardness: 0.35, sound: 'soil' });
def(B.MOSS, 'moss', 'Musgo Estelar', [L.MOSS_TOP, L.MOSS_SIDE, L.SOIL], { hardness: 0.4, sound: 'soil', drop: 'soil' });
def(B.SAND, 'sand', 'Areia', L.SAND, { hardness: 0.3, sound: 'sand' });
def(B.SNOW, 'snow', 'Neve', [L.SNOW, L.SNOW_SIDE, L.SOIL], { hardness: 0.25, sound: 'snow', drop: 'ice' });
def(B.ICE, 'ice', 'Gelo', L.ICE, { hardness: 0.5, sound: 'ice' });
def(B.IRON_ORE, 'iron_ore', 'Minério de Ferro', L.IRON_ORE, { hardness: 1.1, drop: 'iron', ore: true });
def(B.COPPER_ORE, 'copper_ore', 'Minério de Cobre', L.COPPER_ORE, { hardness: 1.0, drop: 'copper', ore: true });
def(B.QUARTZ, 'quartz', 'Cristal de Silício', L.QUARTZ, { hardness: 0.9, drop: 'silicon', ore: true, sound: 'crystal' });
def(B.CARBON, 'carbon', 'Veio de Carbono', L.CARBON, { hardness: 0.8, drop: 'carbon', ore: true });
def(B.TITANIUM_ORE, 'titanium_ore', 'Minério de Titânio', L.TITANIUM_ORE, { hardness: 1.8, drop: 'titanium', ore: true });
def(B.RADITE, 'radite', 'Radita', L.RADITE, { hardness: 1.4, drop: 'radite', ore: true, emissive: 0.35, sound: 'crystal', radiation: 1.2 });
def(B.AURELITE, 'aurelite', 'Aurelita', L.AURELITE, { hardness: 1.3, drop: 'aurelite', ore: true, emissive: 0.9, sound: 'crystal' });
def(B.LAVA, 'lava', 'Lava Solidificando', L.LAVA, { hardness: 1.2, drop: 'basalt', emissive: 2.6 });
def(B.METAL_PLATE, 'metal_block', 'Painel Metálico', L.METAL_PLATE, { hardness: 0.9, sound: 'metal' });
def(B.GLASS, 'glass', 'Vidro Reforçado', L.GLASS, { hardness: 0.5, opaque: false, translucent: true, sound: 'glass' });
def(B.CONCRETE, 'concrete', 'Compósito Estrutural', L.CONCRETE, { hardness: 1.0 });
def(B.LAMP, 'lamp', 'Bloco Luminoso', L.LAMP, { hardness: 0.4, emissive: 3.0, sound: 'glass' });
def(B.SANDSTONE, 'sandstone', 'Arenito', L.SANDSTONE, { hardness: 0.6, drop: 'rock' });
def(B.ASH, 'ash', 'Cinzas', L.ASH, { hardness: 0.3, sound: 'sand', drop: 'sulfur', dropCount: 1 });
def(B.SULFUR, 'sulfur_ore', 'Enxofre', L.SULFUR, { hardness: 0.7, drop: 'sulfur', ore: true, sound: 'crystal' });
def(B.STALK, 'stalk', 'Caule Alienígena', [L.STALK_TOP, L.STALK, L.STALK_TOP], { hardness: 0.5, drop: 'organics', sound: 'organic' });
def(B.CANOPY, 'canopy', 'Copa Bioluminescente', L.CANOPY, { hardness: 0.15, drop: 'organics', sound: 'organic', emissive: 0.25 });
def(B.MUD, 'mud', 'Lama', L.MUD, { hardness: 0.3, sound: 'soil', drop: 'soil' });
def(B.CRYOLITH, 'cryolith', 'Criolita', L.CRYOLITH, { hardness: 1.6, drop: 'cryolith', ore: true, emissive: 0.3, sound: 'crystal' });
def(B.LUMINITE, 'luminite', 'Luminita', L.LUMINITE, { hardness: 1.6, drop: 'luminite', ore: true, emissive: 1.2, sound: 'crystal' });
def(B.REGOLITH, 'regolith', 'Regolito', L.REGOLITH, { hardness: 0.35, sound: 'sand', drop: 'rock' });
def(B.FLOOR, 'floor', 'Piso Técnico', [L.FLOOR, L.METAL_PLATE, L.METAL_PLATE], { hardness: 0.8, sound: 'metal' });
def(B.CORAL, 'coral', 'Coral Mineral', L.CORAL, { hardness: 0.4, drop: 'organics', sound: 'organic', emissive: 0.15 });
def(B.FUNGUS, 'fungus', 'Chapéu Fúngico', L.FUNGUS, { hardness: 0.2, drop: 'organics', sound: 'organic', emissive: 0.6 });
def(B.RED_ROCK, 'red_rock', 'Rocha Ferruginosa', L.RED_ROCK, { hardness: 0.7, drop: 'rock' });
def(B.HULL, 'hull_block', 'Blindagem Escura', L.HULL, { hardness: 1.4, sound: 'metal' });
def(B.MACHINE, 'machine', 'Máquina', 0, { opaque: false, drop: null, hardness: Infinity });
def(B.MACHINE_OPEN, 'machine_open', 'Passagem', 0, { opaque: false, solid: false, drop: null, hardness: Infinity });

const fallback = defs[B.ROCK];
export const BLOCKS: BlockDef[] = [];
for (let i = 0; i < 256; i++) BLOCKS[i] = defs[i] ?? fallback;

export function blockSolid(id: number): boolean {
  return BLOCKS[id].solid;
}

/** Placeable block for an item key (if any). */
export const ITEM_TO_BLOCK: Record<string, number> = {
  rock: B.ROCK, basalt: B.BASALT, soil: B.SOIL, sand: B.SAND, ice: B.ICE,
  metal_block: B.METAL_PLATE, glass: B.GLASS, concrete: B.CONCRETE, lamp: B.LAMP,
  floor: B.FLOOR, hull_block: B.HULL,
};

/** Packed lookup tables for fast access in the mesher. */
export const BLOCK_OPAQUE = new Uint8Array(256);
export const BLOCK_TRANSLUCENT = new Uint8Array(256);
export const BLOCK_SOLID = new Uint8Array(256);
export const BLOCK_LAYERS = new Uint8Array(256 * 3);
export const BLOCK_EMISSIVE = new Float32Array(256);
for (let i = 0; i < 256; i++) {
  const b = BLOCKS[i];
  BLOCK_OPAQUE[i] = b.opaque ? 1 : 0;
  BLOCK_TRANSLUCENT[i] = b.translucent ? 1 : 0;
  BLOCK_SOLID[i] = b.solid ? 1 : 0;
  BLOCK_LAYERS[i * 3] = b.top;
  BLOCK_LAYERS[i * 3 + 1] = b.side;
  BLOCK_LAYERS[i * 3 + 2] = b.bottom;
  BLOCK_EMISSIVE[i] = b.emissive;
}
BLOCK_OPAQUE[B.UNKNOWN] = 1;
BLOCK_SOLID[B.UNKNOWN] = 1;
